version: "3.8"

x-airflow-common: &airflow-common
  image: apache/airflow:2.8.1-python3.11
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    AIRFLOW__CORE__FERNET_KEY: "81HqDtbqAywKSOumSha3BhWNOdQ26slT6K0YaZeZyPs="
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__WEBSERVER__SECRET_KEY: "uk-pipeline-secret-key"
    PYTHONPATH: "/opt/airflow"
  volumes:
    - ./dags:/opt/airflow/dags
    - ./ingestion:/opt/airflow/ingestion
    - ./data:/opt/airflow/data
    - ./logs:/opt/airflow/logs
    - ./dbt_ons:/opt/airflow/dbt_ons
    - ./.env:/opt/airflow/.env
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      POSTGRES_MULTIPLE_DATABASES: airflow,ons_pipeline
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
    ports:
      - "5432:5432"

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "
        pip install dbt-core dbt-postgres pandas requests pyarrow python-dotenv &&
        airflow db migrate &&
        airflow users create --username admin --password admin
          --firstname Arun --lastname Ravi
          --role Admin --email arunraviauto@gmail.com
      "
    restart: on-failure

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

volumes:
  postgres_data:
