ons_pipeline:
  target: dev
  outputs:
    dev:
      type:     postgres
      host:     postgres
      port:     5432
      user:     airflow
      password: airflow
      dbname:   ons_pipeline
      schema:   public
      threads:  2
